/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tedneward.lolcode

import com.tedneward.lolcode.ast.*

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class InterpreterTests {
    @Test fun versionTest() {
        val interp = Interpreter()
        assertEquals(interp.version(), "0.1")
    }

    @Test fun evaluateBinaryOp() {
        val interp = Interpreter()

        val expr = BinaryOp(Atom("2"), BinaryOp.Operator.ADD, Atom("4"))

        val result = interp.evaluate(expr)
        assertEquals(6, result.asInt64())
    }
}
