HAI

I HAS A num ITZ SUM OF 2 AN 2
VISIBLE num MKAY?

I HAS A num2 ITZ DIFF OF 2 AN 2
VISIBLE num2 MKAY?

I HAS A num3 ITZ PRODUKT OF 10 AN 10
VISIBLE num3 MKAY?

I HAS A num4 ITZ QUOSHUNT OF 10 AN 2
VISIBLE num4 MKAY?

I HAS A num5 ITZ MOD OF 4 AN 2
VISIBLE num5 MKAY?

SUM OF 2 AN 2

KTHXBYE
