/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tedneward.lolcode

import java.util.Stack
import org.antlr.v4.runtime.*
import org.antlr.v4.runtime.tree.ParseTree
import org.antlr.v4.runtime.tree.ParseTreeWalker

// ====================================
// Abstract Syntax Tree
open class ASTNode(val children: MutableList<ASTNode> = mutableListOf()) { 
    override fun toString() : String {
        val mappedChildren = children.map { "(" + it.toString() + ")" }
        return "(${mappedChildren})"
    }
}
class CodeBlock() : ASTNode() { }
class Program(var version: String = "", var codeBlock: CodeBlock = CodeBlock()) : ASTNode() { 
    override fun toString() : String {
        return "(program version:${version} codeBlock:${codeBlock})"
    }
}
class Declaration() : ASTNode() { 
    var name = ""
    var initialValue = ""
    override fun toString() : String {
        return "(decl ${name} ${initialValue})"
    }
}

class ASTBuilder() : lolcodeBaseListener() {
    val program = Program()
    var blockStack = Stack<CodeBlock>()

    override fun enterProgram(ctx : lolcodeParser.ProgramContext) { 
        program.version = if (ctx.opening().version() != null) ctx.opening().version().getText() else "1.2";
    }
    override fun enterCode_block(ctx : lolcodeParser.Code_blockContext) {
        val codeBlock = if (blockStack.isEmpty()) program.codeBlock else CodeBlock()
        blockStack.push(codeBlock)
    }
    override fun exitCode_block(ctx : lolcodeParser.Code_blockContext) {
        blockStack.pop()
    }
    override fun enterDeclaration(ctx : lolcodeParser.DeclarationContext) {
        val decl = Declaration()
        
        decl.name = ctx.LABEL().text
        if (ctx.expression() != null)
            decl.initialValue = ctx.expression().text

        blockStack.peek().children.add(decl);
    }
}

// ====================================
// Interpreter
class Interpreter {
    var program : Program = Program()

    fun version() : String { return "0.1" }

    fun run(program : Program) {
        this.program = program
    }
    fun execute(code : String) {
        val lexer = lolcodeLexer(CharStreams.fromString(code))
        val tokens = CommonTokenStream(lexer)
        val parser = lolcodeParser(tokens)
        val builder = ASTBuilder()
        ParseTreeWalker.DEFAULT.walk(builder, parser.program())
        System.out.println("AST: ${builder.program}")
        return run(builder.program)
    }
}
